name: cargo_run
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.2+4

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  another_stepper: ^1.2.2
  # auto_route: ^9.2.2
  chat_bubbles: ^1.5.0
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.9
  flutter_svg: ^2.0.9
  get_it: ^7.6.7
  givestarreviews: ^1.0.2
  google_fonts: ^6.1.0
  group_button: ^5.3.4
  http: ^1.2.0
  iconsax: ^0.0.8
  intl: 
  otp_text_field: ^1.1.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  webview_flutter: ^4.11.0
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.1.7
  geolocator: ^10.1.0
  # geocoding: ^3.0.0
  socket_io_client: ^2.0.3+1
  nb_utils:
    git:
      url: https://github.com/yusuf-umarr/nb_utils.git
  # awesome_notifications: 
  upgrader:
  cached_network_image: ^3.3.0
  image_picker: ^1.0.1
  rename: ^3.0.2
    # packageInfo
  package_info_plus: ^8.2.1
  step_progress_indicator: ^1.0.2
  # geocoding: ^3.0.0
  share_plus: ^10.1.2
  screenshot: ^3.0.0
  # image_gallery_saver_plus: ^4.0.1
  permission_handler: ^11.3.1
  awesome_notifications: ^0.10.1
  url_launcher: ^6.3.1


  

  


dev_dependencies:
  # auto_route_generator: 
  build_runner:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

dependency_overrides:
  archive: ^3.6.1
  win32: ^5.5.3

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
  uses-material-design: true
  assets:
    - assets/images/
  


flutter_native_splash:
  color: "#1034A6"
  image: assets/images/bg.png

  android_12:
    color: "#1034A6"
    image: assets/images/bg.png

  android: true
  ios: true
  #web: false
  # Platform specific images can be specified with the following parameters, which will override
  # the respective parameter.  You may specify all, selected, or none of these parameters:
  #color_android: "#42a5f5"
  #color_dark_android: "#042a49"
  #color_ios: "#42a5f5"
  #color_dark_ios: "#042a49"
  #color_web: "#42a5f5"
  #color_dark_web: "#042a49"
  #image_android: assets/splash-android.png
  #image_dark_android: assets/splash-invert-android.png
  #image_ios: assets/splash-ios.png
  #image_dark_ios: assets/splash-invert-ios.png
  #image_web: assets/splash-web.gif
  #image_dark_web: assets/splash-invert-web.gif
  #background_image_android: "assets/background-android.png"
  #background_image_dark_android: "assets/dark-background-android.png"
  #background_image_ios: "assets/background-ios.png"
  #background_image_dark_ios: "assets/dark-background-ios.png"
  #background_image_web: "assets/background-web.png"
  #background_image_dark_web: "assets/dark-background-web.png"
  #branding_android: assets/brand-android.png
  #branding_dark_android: assets/dart_dark-android.png
  #branding_ios: assets/brand-ios.png
  #branding_dark_ios: assets/dart_dark-ios.png
  #branding_web: assets/brand-web.gif
  #branding_dark_web: assets/dart_dark-web.gif
  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center
  # The screen orientation can be set in Android with the android_screen_orientation parameter.
  # Valid parameters can be found here:
  # https://developer.android.com/guide/topics/manifest/activity-element#screen
  #android_screen_orientation: sensorLandscape
  # To hide the notification bar, use the fullscreen parameter.  Has no effect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: [SystemUiOverlay.bottom, SystemUiOverlay.top], );
  #fullscreen: true
  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
